#! /bin/bash

# Note: An auto-complete script for 'see'(SeeThem)

# ===
# === Completion List
# ===
complete -W "\
    viewmode\
    column_ratios\
    hidden_filter\
    show_hidden\
    confirm_on_delete\
    use_preview_script\
    preview_script\
    automatically_count_files\
    open_all_images\
    vcs_aware\
    vcs_backend_git\
    vcs_backend_hg\
    vcs_backend_bzr\
    vcs_backend_svn\
    preview_images\
    preview_images_method\
    w3m_delay\
    iterm2_font_width\
    iterm2_font_height\
    unicode_ellipsis\
    bidi_support\
    show_hidden_bookmarks\
    colorscheme\
    preview_files\
    preview_directories\
    collapse_preview\
    save_console_history\
    status_bar_on_top\
    draw_progress_bar_in_status_bar\
    draw_borders\
    dirname_in_tabs\
    mouse_enabled\
    display_size_in_main_column\
    display_size_in_status_bar\
    display_free_space_in_status_bar\
    display_tags_in_all_columns\
    update_title\
    update_tmux_title\
    shorten_title\
    hostname_in_titlebar\
    tilde_in_titlebar\
    max_history_size\
    max_console_history_size\
    scroll_offset\
    flushinput\
    padding_right\
    autosave_bookmarks\
    save_backtick_bookmark\
    autoupdate_cumulative_size\
    show_cursor\
    sort\
    sort_reverse\
    sort_case_insensitive\
    sort_directories_first\
    sort_unicode\
    xterm_alt_key\
    cd_bookmarks\
    cd_tab_case\
    cd_tab_fuzzy\
    preview_max_size\
    hint_collapse_threshold\
    show_selection_in_titlebar\
    idle_delay\
    metadata_deep_search\
    clear_filters_on_dir_change\
    line_numbers\
    relative_current_zero\
    one_indexed\
    save_tabs_on_exit\
    wrap_scroll\
    global_inode_type_filter\
    freeze_files\
    " see
